services:
  postgres:
    image: postgres:17
    restart: on-failure
    # container_name: ${DOCKER_CONTAINER}   # optional, letting Docker handle names avoids conflicts
    env_file:
      - .env
    environment:
      # - POSTGRES_DB=${POSTGRES_SCHEMA}    # unused, keeping DB name from POSTGRES_DB in .env
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # ports:
    #   - "${HOST_PORT}:5432"
    volumes:
      # - ./:/bootcamp/                    # optional bind mount if needed for dev
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dataplatform_net

  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure
    # container_name: pgadmin              # optional, can cause conflicts if reused
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - dataplatform_net
  
  
  metabase:
    image: metabase/metabase:latest
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DB}
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - dataplatform_net


  minio:
    image: minio/minio
    restart: always
    # container_name: minio                # optional
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # MinIO Console
    volumes:
      - minio-data:/data
    networks:
      - dataplatform_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  mc:
    image: minio/mc
    restart: on-failure
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set localminio http://minio:9000 ${MINIO_USER} ${MINIO_PASSWORD} &&
      /usr/bin/mc mb --ignore-existing localminio/${MINIO_BUCKET_RAW} &&
      /usr/bin/mc mb --ignore-existing localminio/${MINIO_BUCKET_STAGING} &&
      /usr/bin/mc mb --ignore-existing localminio/${MINIO_BUCKET_ARCHIVE} &&
      /usr/bin/mc policy set public localminio/${MINIO_BUCKET_RAW} &&
      /usr/bin/mc policy set public localminio/${MINIO_BUCKET_STAGING} &&
      /usr/bin/mc policy set public localminio/${MINIO_BUCKET_ARCHIVE} &&
      tail -f /dev/null
      "
    networks:
      - dataplatform_net


volumes:
  postgres-data:
  pgadmin-data:
  minio-data:

networks:
  dataplatform_net:
    driver: bridge


